#57/9110/http sem/15
lifthus/RFC-KR pull request #67
Opened 2023-10-09 06:03 UTC by jun673012

#### 🔢 Which issue(s) does this change fix?

#### ⚒️ What does this new feature do?

#### 😮 Why is this change necessary?

#### ⁇ How does it address the issue?

#### ⚠️ What side effects does this change have?

#### ✅ Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- [ ] Build successful

By submitting this pull request, I confirm that my contribution is made under the terms of the Lifthus's policy.

2023-10-10 07:30 UTC, lifthus requested changes

2023-10-10 07:30 UTC, lifthus commented on rfc9110-http-semantics/rfc9110kr.md
> +304 (Not Modified) 상태 코드는 조건부 GET 또는 HEAD 요청이 수신되었으며 조건이 거짓으로 평가되지 않았다면 200 (OK) 응답을 받았을 것으로 나타낸다. 즉, 조건부 요청을 한 클라이언트가 이미 유효한 표현을 가지고 있기 때문에 서버가 대상 리소스의 표현을 전송할 필요가 없다; 따라서 서버는 클라이언트가 저장된 표현을 마치 200
304(Not Modified) 상태 코드는 조건부 GET 혹은 HEAD 요청이 수신됐고 만약 조건이 거짓으로 평가된 사실이 없다면 200(OK) 응답을 발생시켰을 것임을 나타낸다. 다시 말해, 서버는 타겟 리소스의 표현을 전송할 필요 없으며 이는 요청이 요청을 조건부로 만든, 클라이언트가, 이미 유효한 표현을 가졌음을 나타내기 때문이다; 서버는 이리하여 저장된 표현을 200(OK) 응답의 콘텐츠인 것 처럼 사용하도록 클라이언트를 리다이렉트한다.

2023-10-10 11:32 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +응답의 상태 코드는 요청의 결과와 요청이 성공했는지의 여부 및 어떤 콘텐츠가 동봉되어 있는지를 포함한 응답의 의미를 설명하는 세 자리 정수 코드다 (있는 경우). 모든 유효한 상태 코드는 100부터 599까지의 범위 내에 있다.
수정 완료

2023-10-10 11:35 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +프록시는 프록시 자체가 1xx 응답 생성을 요청하지 않는 한 반드시(MUST) 1xx 응답을 전달해야 한다. 예를 들어 프록시가 요청을 전달할 때 “예상: 100-continue” 헤더 필드를 추가하는 경우, 해당 100(Continue) 응답을 전달할 필요가 없다.
수정 완료

2023-10-10 11:37 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +| GET | 목표 리소스 |
수정 완료

2023-10-10 11:37 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +| TRACE | trace가 반환하는 서버가 수신한 요청 메세지 |
수정 완료

2023-10-10 11:37 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +101(Switching Protocols) 상태 코드는 서버가 업그레이드 헤더 필드(7.8절)를 통해 이 연결에서 사용 중인 애플리케이션 프로토콜의 변경에 대한 클라이언트의 요청을 이해하고, 이를 준수할 것임을 나타낸다. 서버는 반드시(MUST) 응답 후에 어떤 프로토콜이 적용될 것인지를 나타내는 업그레이드 헤더 필드를 응답에 생성해야 한다.
수정 완료

2023-10-10 11:39 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +201(Created) 상태 코드는 요청이 완료되어 하나 이상의 새로운 리소스가 생성되었음을 나타낸다. 요청에 의해 생선된 기본 리소스는 응답의 Location 헤더 필드 또는 Location 헤더 필드가 수신되지 않은 경우 대상 URI로 식별된다.
수정 완료

2023-10-10 11:40 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +202 응답은 의도적으로 응답하지 않는다. 이것의 목적은 프로세스가 완료될 때까지 서버에 대한 사용자 에이전트의 연결을 유지할 필요 없이 서버가 다른 프로세스 (아마 하루에 한 번만 실행되는 배치 지향 프로세스) 에 대한 요청을 수락할 수 있도록 하는 것이다. 이 응답과 함께 전송되는 표현은 요청의 현재 상태를 설명하고 사용자에게 요청이 언제 완료될지 예
수정 완료

2023-10-10 11:40 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +203 (Non-Authoritative Information) 상태 코드는 요청이 성공했지만 변환 프로식에 의해 원본 서버의 200 (OK) 응답에서 동봉된 콘텐츠가 수정되었음을 나타낸다 (7.7절). 이 상태 코드를 통해 프록시는 변환이 적용되었을 때 수신자에게 알릴 수 있고, 이 지식은 나중에 콘텐츠와 관련된 의사 결정에 영향을 미칠 수 있다. 예를
수정 완료

2023-10-10 11:41 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +예를 들어, PUT 요청에 대한 응답으로 204 상태 코드가 수신되고 응답에 ETag 필드가 포함하는 경우, PUT이 성공했으며 ETag 필드 값에 대상 리소스의 새로운 표현을 위한 엔티티 태그가 포함한다.
수정 완료

2023-10-10 11:41 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +204 응답을 통해 서버는 대상 리소스에 성공적으로 적용되었음을 나타낼 수 있게 하고, 동시에 사용자 에이전트가 현재의 “문서보기” (있는 경우)에서 이동할 필요가 없음을 암시한다. 서버는 사용자 에이전트가 자제 인터페이스에 따라 사용자에게 성공 여부를 표시하고 활성 표현에 대한 응답으로 새로운 메타데이터 또는 업데이트된 메타데이터를 적용할 것으로 가정한
수정 완료

2023-10-10 11:42 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +205 상태 코드는 추가 콘텐츠가 제공되지 않음을 의미하므로, 서버는 205 응답으로 콘텐츠를 생성해서는 안 된다.
수정 완료

2023-10-10 11:44 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +206 응답을 생성하는 서버는 동일한 요청에 대한 200 (OK) 응답으로 전송되었을 경우, 아래 하위 항목에 필요한 필드 외에 다음과 같은 헤더 필드를 반드시(MUST) 생성해야 한다. 날짜, 캐시-제어, ETag, 만료, 콘텐츠 위치, 등등
수정 완료

2023-10-10 11:44 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +206 응답에 있는 Content-Length 헤더 필드는 이 메세지 콘텐츠의 옥텟 수를 나타내며, 일반적으로 선택한 표현의 전체 길이가 아니다. 각 Content-Range 헤더 필드는 선택한 표현의 전체 길이에 대한 정보가 포함되어 있다.
수정 완료

2023-10-10 11:56 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +여러 부분이 전송되는 경우, 206 응답을 샹성하는 서버는 14.6절에 정의된 대로 “multipart/byteranges” 콘텐츠를 생성하고, “multipart/byteranges” 미디어 타입 및 필수 경계 매개변수를 포함하는 Content-Type 헤더 필드를 반드시(MUST) 생성해야 한다. 단일 부분 응답과의 혼동을 방지하기 위해 서버는 다중
수정 완료

2023-10-10 12:01 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +Heuristic하게 캐시 가능한 것으로 정의된 상태 코드를 갖는 응답은 (예: 본 명세서에서 200, 203, 204, 206, 300, 301, 308, 404, 405, 410, 414, 501) 메서드 정의 또는 명시적 캐시 컨트롤[CACHING]; 에 달리 명시되지 않는 한 Heuristic 만료를 갖는 캐시에 의해 재사용할 수 있으며, 다른 모
수정 완료

2023-10-10 12:01 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +클라이언트는 최종 응답 전에 수신된 하나 이상의 1xx 응답을 클라이언트가 예상하지 못하더라도 반드시(MUST) 파싱할 수 있어야 한다. 사용자 에이전트는 예상지 못한 1xx 응답을 아마(MAY) 무시할 수 있다.
수정 완료

2023-10-10 12:02 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +200 응답은 메소드 정의 또는 명시적 캐시 컨트롤에 달리 명시되지 않는 한 heuristic 하게 캐시할 수 있다. ([CACHING] 4.2.2절 참조)
수정 완료

2023-10-10 12:02 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +203 응답은 메서드 정의 또는 명시적 캐시 컨트롤에 달리 명시되지 않는 한 (4.2.2절 참조 [CACHING]) heuristic하게 캐시 할 수 있다.
수정 완료

2023-10-10 12:03 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +204 응답은 메서드 정의 또는 명시적 캐시 컨트롤에 달리 명시되지 않는 한 (4.2.2절 참조 [CACHING]) heuristic하게 캐시 할 수 있다.
수정 완료

2023-10-10 12:03 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +206 응답은 메서드 정의 또는 명시적 캐시 컨트롤에 달리 명시되지 않는 한 (4.2.2절 참조 [CACHING]) heuristic하게 캐시 할 수 있다.
수정 완료

2023-10-10 12:05 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +여러 범위가 요청될 때, 서버는 수신된 범위 헤더 필드에 해당 범위 사양이 표시된 순서과 관계없이 여러 부분을 전송할 때 발생되는 오버헤드보다 작은 간격으로 중복되거나 분리된 범위 중 하나를 아마(MAY) 합칠 수 있다. "multipart/byteranges"의 각 부분 사이의 일반적인 오버헤드가 약 80 바이트이기 때문에, 선택된 표현의 미디어 타입
수정 완료

2023-10-20 12:31 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +클라이언트는 동일한 자격 증명으로 요청을 웬만하면(SHOULD) 자동으로 반복해서는 안 된다. 클라리언트는 새로운 자격 증명 또는 다른 자격 증명을 사용하여 아마(MAY) 요청울 반복 할 수 있다. 그러나, 자격 증명과 관련이 없는 이유로 요청이 금지될 수 있다.
수정 완료

2023-10-20 12:33 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +308 응답은 메서드 정의 또는 명시적 캐시 컨트롤에 달리 명시되지 않는 한 (4.2.2절 참조 [CACHING]) heuristic하게 캐시 할 수 있다.
수정 완료

2023-10-20 12:35 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +307 (Temporary Redirect) 상태 코드는 대상 리소스가 일시적으로 다른 URI에 존재하는 것을 나타내며, 사용자 에이전트가 해당 URI로 자동 리다이렉션을 수행하는 경우 요청 방법을 절대(MUST NOT) 변경해서는 안 된다는 것을 나타낸다. 리다이렉션은 시간이 지남에 따라 변경될 수 있기 때문에, 클라이언트는 향후 요청을 위해 원래 대상
수정 완료

2023-10-20 12:38 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +304 응답을 수신하는 캐시에 대한 요구 사항은 [CACHING] 4.3.4절에 정의되어 있다. 조건부 요청이 자신의 캐시가 있는 사용자 에이전트가 공유 프록시로 조건부 GET을 전송하는 것과 같이 outbound 클라이언트에서 발생한 경우, 프록시는 304 응답을 해당 클라이언트로 웬만하면(SHOULD) 전달해야 한다.
수정 완료

2023-10-20 12:39 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +304 응답의 목표는 수신자가 이미 하나 이상의 캐시된 표현을 가지고 있을 때 정보 전달을 최소화하는 것 이기 때문에, 송신자는 캐시 업데이트를 안내하기 위한 목적으로 해당 메타데이터가 존재하지 않는 한 나열된 필드 이외의 표현 메타데이터를 웬만해서는(SHOULD NOT) 생성해서는 안 된다 (예: 응답에 ETag 필드가 없는 경우 Last-Modifie
수정 완료

2023-10-20 12:40 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
>  - Cache-Control and Expires (see [CACHING])
수정 완료

2023-10-20 12:40 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
>  - Content-Location, Date, ETag, and Vary
수정 완료

2023-10-20 12:41 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +304 응답을 생성하는 서버는 동일한 요청에 대해 200 (OK) 응답으로 전송되는 다음 헤더 필드 중 하나를 반드시(MUST) 생성해야 한다:
수정 완료

2023-10-20 12:41 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +304 (Not Modified) 상태 코드는 조건부 GET 또는 HEAD 요청이 수신되었으며 조건이 거짓으로 평가되지 않았다면 200 (OK) 응답을 받았을 것으로 나타낸다. 즉, 조건부 요청을 한 클라이언트가 이미 유효한 표현을 가지고 있기 때문에 서버가 대상 리소스의 표현을 전송할 필요가 없다; 따라서 서버는 클라이언트가 저장된 표현을 마치 200
수정 완료

2023-10-20 12:42 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +GET 요청에 대한 303 응답은 origin 서버가 HTTP를 통해 서버가 전송할 수 있는 대상 리소스의 표현을 가지고 있지 않음을 나타낸다. 그러나, Location 필드 값은 대상 리소스를 설명하는 리소스를 참조하므로 다른 리소스에 대한 검색 요청을 하면 원래 대상 리소스를 나타내지 않으면서도 수신자에게 유용한 표현이 될 수 있다. 무엇을 표현할 수
수정 완료

2023-10-20 12:42 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +303 (See Other) 상태 코드는 서버가 사용자 에이전트를 다른 리소스로 리다이렉션하고 있음을 나타내며, 이것은 원래 요청에 대한 간접 응답을 제공하기 위해 Location 헤더 필드에 있는 URI로 표시된다. 사용자 에이전트는 리다이렉션될 수도 있는 해당 URI(HTTP를 사용하는 경우 GET 또는 HEAD 요청) 를 대상으로 검색 요청을 수행하
수정 완료

2023-10-20 12:43 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +302 (Found) 상태 코드는 대상 리소스가 일시적으로 다른 URI에 존재함울 나타낸다. 리다이렉션은 종종 변경될 수 있기 때문에, 클라이언트는 향후 요청을 위해 대상 URI를 계속 사용해야 한다.
수정 완료

2023-10-20 12:45 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +301 (Moved Permanently) 상태 코드는 대상 리소스에 새로운 영구 URI가 할당되었음을 나타내며 이 리소스에 대한 향후 참조는 동봉된 URI 중 하나를 사용해야 한다. 서버는 링크 편집 기능이 있는 사용자 에이전트가 대상 URI에 대한 참조를 서버가 보낸 새로운 참조 중 하나로 영구적으로 대체할 수 있다고 제안한다. 그러나, 사용자 에이전
수정 완료

2023-10-20 12:48 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +HEAD 이외의 요청 메소드의 경우, 서버는 사용자 또는 사용자 에이전트가 가장 선호하는 것을 선택할수 있는 표현 메타데이터 및 URI 참조 목록이 포함된 콘텐츠를 300응답에 웬만하면(SHOULD) 생성해야 한다. 사용자 에이전트가 제공된 미디어 유형을 이해하는 경우 해당 목록에서 자동으로 선택할 수 있다. HTTP는 콘텐츠의 정의에 직교를 유지하려고
수정 완료

2023-10-20 12:50 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +서버에 기본 설정이 있는 경우, 서버는 기본 설정의 URI 참조가 포함된 Location 헤더 필드를 생성해야 한다. 사용자 에이전트는 자동 리다이렉션을 위해 Location 필드 값을 사용할 수 있다.
수정 완료

2023-10-20 12:51 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +클라이언트는 주기적 리다이렉션(즉, “무한” 리다이렉션 루프) 을 웬만하면(SHOULD) 감지하고 개입해야 한다.
수정 완료

2023-10-20 12:51 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +5.  요청 메소드가 GET 또는 HEAD로 변경된 경우, Content-Encoding, Content-Language, Content-Location, Content-Type, Content-Length, Digest, Last-Modified (이에 제한되지 않음) 콘텐츠별 헤더 필드를 제거합니다.
수정 완료

2023-10-20 12:52 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +    4.  구현 캐시에 의해 추가된 헤더 필드(예: If-None-Match, If-Modified-Since)의 유효성 검사, 및
수정 완료

2023-10-20 12:52 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +    3.  Origin-별 헤더 필드(있는 경우), 호스트를 포함한(이에 제한되지 않음),
수정 완료

2023-10-20 12:53 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +1.  원본 요청의 대상 URI를 기준으로 확인한 후 리디렉션 응답의 위치 헤더 필드 값에서 참조하는 URI로 대상 URI를 바꾼다.
수정 완료

2023-10-20 12:55 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +3.  303 (See Other) 상태 코드와 같이 요청에 대한 간접적인 응답을 나타낼 수 있는 위치 헤더 필드로 식별되는 다른 리소스로 리다이렉션한다.
수정 완료

2023-10-20 12:55 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +2.  300 (Multiple Choices) 상태 코드와 같이 이 리소스를 나타낼 수 있는 일치하는 리소스 중에서 선택할 수 있는 리다이렉션이다.
수정 완료

2023-10-20 12:55 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +1.  Redirects 상태 코드 301 (Moved Permanently), 302 (Found), 307 (Temporary Redirect), 및 308 (Permanent Redirect) 과 같이 위치 헤더 필드에 제공된 대로 이 리소스를 다른 URI에서 사용할 수 있음을 나타내는 리다이렉션이다.
수정 완료

2023-10-20 12:55 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +상태 코드의 3xx (Redirection) 클래스는 요청을 이행하기 위해 사용자 에이전트가 추가 조취를 취할 필요가 있음을 나타낸다. redirects에는 여러 유형이 있다:
수정 완료

2023-10-20 12:56 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +결합된 응답 콘텐츠는 새로운 응답 내의 부분 콘텐츠의 범위와 일치하는 모든 저장된 응답의 결합으로 구성된다. 결합이 전체 범위의 표현의로 구성된 경우, 클라이언트는 전체 길이를 반영하는 Content-Length 헤더 필드를 포함하여 결합된 응답을 완전한 200(OK) 응답인 것처럼 반드시(MUST) 처리해야 한다. 그렇지 않으면 클라이언트는 연속 범위
수정 완료

2023-10-20 12:56 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +가장 최근 응답이 206(Partial Content) 응답이고, 일치하는 저장된 응답 중 하나 이상이 200(OK) 인 경우, 결합된 응답 헤더 필드는 가장 최근 200 응답의 헤더 필드로 구성된다. 일치하는 모든 저장된 응답이 206 응답인 경우, 가장 최근의 헤더 필드를 가진 저장된 응답은 결합된 응답의 헤더 필드 소스로 사용되지만, 클라이언트는 저
수정 완료

2023-10-20 12:56 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +타켓 리소스에 대한 GET 요청에 대해 여러 부분을 받은 클라이언트는 동일한 강력한 검증자를 공유하는 경우 아마(MAY) 해당 응답을 더 큰 연속 범위로 결합할 수 있다.
수정 완료

2023-10-20 12:57 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +다중 파트 응답을 생성하는 서버는 수신된 범위 헤더 필드에 대한 범위 사양이 표시된 순서대로 파트를 웬만하면(SHOULD) 보내야 하며, 만족스럽지 않은 것으로 간주되거나 다른 범위로 합쳐진 범위는 제외해야 한다. 다중 파트 응답을 수신하는 클라이언트는 각 body 파트에 있는 Content-Range 헤더 필드를 반드시(MUST) 검사하여 해당 body
수정 완료

2023-10-22 03:35 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +여러 부분을 요청하지 않는 클라이언트는 다중 부분 응답을 지원하지 않을 수 있으므로 서버는 단일 범위에 대한 요청에 대해 다중 부분 응답을 생성해서는 안 된다. 그러나, 여러 범위가 요청되었으나 하나의 범위만이 만족스러운 것으로 확인되거나 합쳐진 후 하나의 범위만 남은 경우 서버는 단일 body 부분으로만 "multipart/byteranges" 응답을
수정 완료

2023-10-22 03:37 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +      |  *Note:* 과거의 이유로, 사용자 에이전트는 후속 요청에 대해
수정 완료

2023-10-22 03:37 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +      |  *Note:* 과거의 이유로, 사용자 에이전트는 후속 요청에 대해
수정 완료

2023-10-22 03:38 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +      |  *Note:* 이 상태 코드는 sibling 코드들보다 휠씬 나중이므로 (2014년 6월)
수정 완료

2023-10-22 03:39 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +305 (Use Proxy) 상태 코드는 이 명세서의 이전 버전에서 정의되었으며 현재는 더 이상 사용되지 않는다 ([RFC7231]의 부록 B).
수정 완료

2023-10-22 03:40 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +      |  *Note:* 300 상태 코드에 대한 원래 제안에서는 URI 헤더 필드가 200, 300 및 406 응답에 사용할 수 있고
수정 완료

2023-10-22 03:40 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +      |  *Note:* 이 사양의 이전 버전에서는 최대 5개의 리다이렉션을 권장했다([RFC2068], 10.3절).
수정 완료

2023-10-22 03:42 UTC, jun673012 commented on rfc9110-http-semantics/rfc9110kr.md
> +    | _Note:_ HTTP/1.0에서 상태 코드 301 (Moved Permanently) 과 302 (Found)는 원래 메서드 보존
수정 완료

2023-10-22 04:19 UTC, lifthus requested changes
**Note:** 이거 왼쪽에 들여쓰기 짝대기들 없애고 노트에서 이어지는 한줄로 되고 Note는 ** ** 마크다운으로 볼드체 처리되야함.

2023-10-22 04:30 UTC, lifthus approved these changes
굳

2023-10-22 04:30 UTC, merged